/*
 * Copyright (C) 2018 Wouter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.dndbattle.view.master.armor;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;

import org.dndbattle.objects.impl.Armor;
import org.dndbattle.utils.Armors;
import org.dndbattle.utils.Settings;
import org.dndbattle.view.IUpdateablePanel;

/**
 *
 * @author Wouter
 */
public class ArmorsPanel extends javax.swing.JPanel implements IUpdateablePanel {

    private static final Settings SETTINGS = Settings.getInstance();
    private static final Armors ARMORS = Armors.getInstance();
    private static final String DIVIDER_LOCATION_PROPERTY = "gui.master.presetpanel.armors.deviderlocation";

    public ArmorsPanel() {
        initComponents();
        update();
    }

    @Override
    public final void update() {
        Armor selection = (Armor) lArmors.getSelectedValue();

        DefaultListModel<Armor> model = (DefaultListModel<Armor>) lArmors.getModel();
        model.removeAllElements();

        ARMORS.getAll().stream().filter((armor) -> (armor instanceof Armor)).forEachOrdered((armor) -> {
            model.addElement((Armor) armor);
        });

        if (selection
                != null) {
            lArmors.setSelectedValue(selection, true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        spArmors = new javax.swing.JSplitPane();
        pArmorList = new javax.swing.JPanel();
        spArmorsList = new javax.swing.JScrollPane();
        lArmors = new javax.swing.JList<Armor>();
        bNew = new javax.swing.JButton();
        spEdit = new javax.swing.JScrollPane();

        spArmors.setDividerLocation(SETTINGS.getProperty(DIVIDER_LOCATION_PROPERTY, 150));
        spArmors.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                spArmorsPropertyChange(evt);
            }
        });

        pArmorList.setLayout(new java.awt.GridBagLayout());

        lArmors.setModel(new DefaultListModel<Armor>());
        lArmors.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lArmors.setToolTipText("");
        lArmors.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lArmorsValueChanged(evt);
            }
        });
        spArmorsList.setViewportView(lArmors);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        pArmorList.add(spArmorsList, gridBagConstraints);

        bNew.setText("New");
        bNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        pArmorList.add(bNew, gridBagConstraints);

        spArmors.setLeftComponent(pArmorList);
        spArmors.setRightComponent(spEdit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spArmors, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spArmors, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lArmorsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lArmorsValueChanged
        Armor selection = lArmors.getSelectedValue();
        if (!evt.getValueIsAdjusting() && selection != null) {
            spEdit.setViewportView(new ArmorPanel(selection, this));
        }
    }//GEN-LAST:event_lArmorsValueChanged

    private void bNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewActionPerformed
        String input = JOptionPane.showInputDialog(this, "Please enter a name for the armor.", "Please enter name", JOptionPane.QUESTION_MESSAGE);
        if (input != null && !input.isEmpty()) {
            Armor armor = new Armor();
            armor.setName(input);
            if (ARMORS.add(armor)) {
                update();
                lArmors.setSelectedValue(armor, true);
            }
        }
    }//GEN-LAST:event_bNewActionPerformed

    private void spArmorsPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_spArmorsPropertyChange
        if (evt.getPropertyName().equalsIgnoreCase(JSplitPane.DIVIDER_LOCATION_PROPERTY)) {
            SETTINGS.setProperty(DIVIDER_LOCATION_PROPERTY, spArmors.getDividerLocation());
        }
    }//GEN-LAST:event_spArmorsPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bNew;
    private javax.swing.JList<Armor> lArmors;
    private javax.swing.JPanel pArmorList;
    private javax.swing.JSplitPane spArmors;
    private javax.swing.JScrollPane spArmorsList;
    private javax.swing.JScrollPane spEdit;
    // End of variables declaration//GEN-END:variables
}
