/*
 * Copyright (C) 2018 wverl
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wouter.dndbattle.view.slave.character;

import com.wouter.dndbattle.objects.impl.Spell;
import com.wouter.dndbattle.utils.GlobalUtils;
import java.awt.event.ItemEvent;

/**
 *
 * @author wverl
 */
public class SlaveSpellPanel extends javax.swing.JPanel {

    public static final int PREFERED_WIDTH;

    static {
        PREFERED_WIDTH = new SlaveSpellPanel().getPreferredSize().width;
    }

    private final Spell spell;
    private final SlaveSpellOverviewPanel overviewPanel;

    private SlaveSpellPanel() {
        spell = new Spell();
        overviewPanel = null;
        initComponents();
    }

    public SlaveSpellPanel(Spell spell, SlaveSpellOverviewPanel overviewPanel) {
        this.spell = spell;
        this.overviewPanel = overviewPanel;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lName = new javax.swing.JLabel();
        pInformation = new javax.swing.JPanel();
        lCastingTime = new javax.swing.JLabel();
        lRange = new javax.swing.JLabel();
        lComponents = new javax.swing.JLabel();
        lDuraction = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lLevel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lName.setText(spell.getName());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lName, gridBagConstraints);

        pInformation.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        lCastingTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lCastingTime.setText(spell.getCastingTime());
        lCastingTime.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Casting Time", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pInformation.add(lCastingTime);

        lRange.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lRange.setText(spell.getRange());
        lRange.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Range", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pInformation.add(lRange);

        lComponents.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lComponents.setText(spell.getComponents());
        lComponents.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Components", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pInformation.add(lComponents);

        lDuraction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lDuraction.setText(spell.getDuration());
        lDuraction.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Duration", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));
        pInformation.add(lDuraction);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(pInformation, gridBagConstraints);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(spell.getDescription());
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(jScrollPane1, gridBagConstraints);

        lLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLevel.setText(spell.getLevel().toString());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 5);
        add(lLevel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lCastingTime;
    private javax.swing.JLabel lComponents;
    private javax.swing.JLabel lDuraction;
    private javax.swing.JLabel lLevel;
    private javax.swing.JLabel lName;
    private javax.swing.JLabel lRange;
    private javax.swing.JPanel pInformation;
    // End of variables declaration//GEN-END:variables
}
