version: 2
updates:
- package-ecosystem: maven
  directory: "/dndbattle"
  schedule:
    interval: daily
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.openhtmltopdf:openhtmltopdf-pdfbox
    versions:
    - 1.0.6
    - 1.0.7
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
- package-ecosystem: maven
  directory: "/randomizer"
  schedule:
    interval: daily
    timezone: Europe/Paris
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: joda-time:joda-time
    versions:
    - 2.10.9
