/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wouter.dndbattle.view.master;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

import com.wouter.dndbattle.core.IMaster;
import com.wouter.dndbattle.core.impl.Master;
import com.wouter.dndbattle.objects.ICharacter;
import com.wouter.dndbattle.objects.ICombatant;
import com.wouter.dndbattle.objects.impl.Combatant;
import com.wouter.dndbattle.utils.Settings;
import com.wouter.dndbattle.view.comboboxes.ClassComboBox;
import com.wouter.dndbattle.view.slave.character.SlaveCharacterPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import static com.wouter.dndbattle.utils.Settings.MASTER_LOCATION_X;
import static com.wouter.dndbattle.utils.Settings.MASTER_LOCATION_Y;
import static com.wouter.dndbattle.utils.Settings.MASTER_SIZE_HEIGHT;
import static com.wouter.dndbattle.utils.Settings.MASTER_SIZE_STATE;
import static com.wouter.dndbattle.utils.Settings.MASTER_SIZE_WIDTH;
import static com.wouter.dndbattle.utils.Settings.MASTER_TITLE;

/**
 *
 * @author Wouter
 */
public class MasterFrame extends javax.swing.JFrame {

    private static final Logger log = LoggerFactory.getLogger(MasterFrame.class);
    private static final Settings SETTINGS = Settings.getInstance();

    private final Master master;

    /**
     * Creates new form MasterFrame
     */
    public MasterFrame() {
        master = new Master(this);
        initComponents();
        spCombatants.getVerticalScrollBar().setUnitIncrement(20);
        setLocation(SETTINGS.getProperty(MASTER_LOCATION_X, Integer.MIN_VALUE), SETTINGS.getProperty(MASTER_LOCATION_Y, Integer.MIN_VALUE));
        setSize(SETTINGS.getProperty(MASTER_SIZE_WIDTH, getPreferredSize().width), SETTINGS.getProperty(MASTER_SIZE_HEIGHT, getPreferredSize().height));
        setExtendedState(SETTINGS.getProperty(MASTER_SIZE_STATE, 0));
        Rectangle screenBounds = getScreenBounds();
        final Rectangle bounds = this.getBounds();
        if (!screenBounds.contains(bounds)) {
            log.debug("Frame brounds [{}] are not within screen bounds [{}]", bounds, screenBounds);
            setLocationRelativeTo(null);
        }
    }

    private Rectangle getScreenBounds() {
        Rectangle bounds = new Rectangle(0, 0, 0, 0);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice lstGDs[] = ge.getScreenDevices();
        for (GraphicsDevice gd : lstGDs) {
            bounds.add(gd.getDefaultConfiguration().getBounds());
        }
        return bounds;
    }

    public IMaster getMaster() {
        return master;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpBase = new javax.swing.JTabbedPane();
        pView = new javax.swing.JPanel();
        tpBattle = new javax.swing.JTabbedPane();
        pMain = new javax.swing.JPanel();
        bAddCombatant = new javax.swing.JButton();
        bNext = new javax.swing.JButton();
        bNewBattle = new javax.swing.JButton();
        spCombatants = new javax.swing.JScrollPane();
        pCombatants = new javax.swing.JPanel();
        tpCharacters = new javax.swing.JTabbedPane();
        pAudio = new com.wouter.dndbattle.view.master.AudioPanel();
        spDice = new javax.swing.JScrollPane();
        dicePanel = new com.wouter.dndbattle.view.master.DicePanel();
        spSettings = new javax.swing.JScrollPane();
        settingsPanel = new com.wouter.dndbattle.view.master.SettingsPanel();
        pClients = new javax.swing.JPanel();
        spClientsTable = new javax.swing.JScrollPane();
        tClients = new javax.swing.JTable();
        bKickClient = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mView = new javax.swing.JMenu();
        miBattle = new javax.swing.JMenuItem();
        miCharacters = new javax.swing.JMenuItem();
        miDice = new javax.swing.JMenuItem();
        miAudio = new javax.swing.JMenuItem();
        miSettings = new javax.swing.JMenuItem();
        sMenu1 = new javax.swing.JPopupMenu.Separator();
        miClients = new javax.swing.JMenuItem();
        sMenu2 = new javax.swing.JPopupMenu.Separator();
        miShutdown = new javax.swing.JMenuItem();

        tpBase.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tpBase.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpBaseStateChanged(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(SETTINGS.getProperty(MASTER_TITLE, "Master").toString());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pView.setLayout(new java.awt.CardLayout());

        bAddCombatant.setText("Add combatant");
        bAddCombatant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddCombatantActionPerformed(evt);
            }
        });

        bNext.setText("Next round");
        bNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNextActionPerformed(evt);
            }
        });

        bNewBattle.setText("New Battle");
        bNewBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNewBattleActionPerformed(evt);
            }
        });

        spCombatants.setBorder(null);

        pCombatants.setLayout(new javax.swing.BoxLayout(pCombatants, javax.swing.BoxLayout.Y_AXIS));
        spCombatants.setViewportView(pCombatants);

        javax.swing.GroupLayout pMainLayout = new javax.swing.GroupLayout(pMain);
        pMain.setLayout(pMainLayout);
        pMainLayout.setHorizontalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bAddCombatant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bNext, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bNewBattle)
                .addContainerGap())
            .addComponent(spCombatants)
        );
        pMainLayout.setVerticalGroup(
            pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bNewBattle)
                    .addComponent(bAddCombatant)
                    .addComponent(bNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spCombatants, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE))
        );

        spCombatants.getAccessibleContext().setAccessibleName("");

        tpBattle.addTab("Battle", pMain);

        pView.add(tpBattle, "Battle");

        tpCharacters.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpCharactersStateChanged(evt);
            }
        });

        addTabsToTpCharacter();

        pView.add(tpCharacters, "Characters");
        pView.add(pAudio, "Audio");

        spDice.setViewportView(dicePanel);

        pView.add(spDice, "Dice");

        spSettings.setViewportView(settingsPanel);

        pView.add(spSettings, "Settings");

        tClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IP", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tClients.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tClients.getTableHeader().setReorderingAllowed(false);
        spClientsTable.setViewportView(tClients);

        bKickClient.setText("Kick");
        bKickClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKickClientActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pClientsLayout = new javax.swing.GroupLayout(pClients);
        pClients.setLayout(pClientsLayout);
        pClientsLayout.setHorizontalGroup(
            pClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pClientsLayout.createSequentialGroup()
                .addComponent(spClientsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bKickClient)
                .addContainerGap())
        );
        pClientsLayout.setVerticalGroup(
            pClientsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spClientsTable, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
            .addGroup(pClientsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bKickClient)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pView.add(pClients, "Clients");
        pClients.getAccessibleContext().setAccessibleName("Clients");

        mView.setText("View");

        miBattle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK));
        miBattle.setText("Battle");
        miBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBattleActionPerformed(evt);
            }
        });
        mView.add(miBattle);

        miCharacters.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        miCharacters.setText("Characters");
        miCharacters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCharactersActionPerformed(evt);
            }
        });
        mView.add(miCharacters);

        miDice.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        miDice.setText("Dice");
        miDice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDiceActionPerformed(evt);
            }
        });
        mView.add(miDice);

        miAudio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        miAudio.setText("Audio");
        miAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAudioActionPerformed(evt);
            }
        });
        mView.add(miAudio);

        miSettings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        miSettings.setText("Settings");
        miSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSettingsActionPerformed(evt);
            }
        });
        mView.add(miSettings);
        mView.add(sMenu1);

        miClients.setText("Clients");
        miClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientsActionPerformed(evt);
            }
        });
        mView.add(miClients);
        mView.add(sMenu2);

        miShutdown.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        miShutdown.setText("Shutdown");
        miShutdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miShutdownActionPerformed(evt);
            }
        });
        mView.add(miShutdown);

        jMenuBar1.add(mView);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        if (getExtendedState() == NORMAL) {
            SETTINGS.setProperty(MASTER_LOCATION_X, getLocation().x);
            SETTINGS.setProperty(MASTER_LOCATION_Y, getLocation().y);
        }
    }//GEN-LAST:event_formComponentMoved

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if (getExtendedState() == NORMAL) {
            SETTINGS.setProperty(MASTER_SIZE_HEIGHT, getHeight());
            SETTINGS.setProperty(MASTER_SIZE_WIDTH, getWidth());
        }
        if (getExtendedState() != ICONIFIED) {
            SETTINGS.setProperty(MASTER_SIZE_STATE, getExtendedState());
        }
    }//GEN-LAST:event_formComponentResized

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        master.shutdown();
    }//GEN-LAST:event_formWindowClosed

    private void tpBaseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpBaseStateChanged
        if (tpBase.getSelectedComponent().equals(tpCharacters)) {
            Component selectedComponent = tpCharacters.getSelectedComponent();
            if (selectedComponent != null) {
                ((MasterCharactersPanel) selectedComponent).updateList();
            }
        }
    }//GEN-LAST:event_tpBaseStateChanged

    private void tpCharactersStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpCharactersStateChanged
        Component selectedComponent = tpCharacters.getSelectedComponent();
        if (selectedComponent != null) {
            ((MasterCharactersPanel) selectedComponent).updateList();
        }
    }//GEN-LAST:event_tpCharactersStateChanged

    private void bNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNextActionPerformed
        master.nextTurn();
    }//GEN-LAST:event_bNextActionPerformed

    private void bAddCombatantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddCombatantActionPerformed
        CombatantSelectionFrame frame = new CombatantSelectionFrame(master);
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
    }//GEN-LAST:event_bAddCombatantActionPerformed

    private void bNewBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNewBattleActionPerformed
        switch (JOptionPane.showConfirmDialog(this,
                "Do you want to carry over the currect combatants with all settings and reroll for initiative?\n"
                + "If you don't want to start a new battle please select cancel.", "Please confirm.", JOptionPane.YES_NO_CANCEL_OPTION)) {
            case JOptionPane.YES_OPTION:
                List<ICombatant> combatants = master.getCombatants();
                for (Iterator<ICombatant> iterator = combatants.iterator(); iterator.hasNext();) {
                    ICombatant combatant = iterator.next();
                    if (combatant.isDead()) {
                        iterator.remove();
                        continue;
                    }
                    int initiative = Integer.MIN_VALUE;
                    while (initiative == Integer.MIN_VALUE) {
                        try {
                            String input = JOptionPane.showInputDialog(this, "Please enter new initiative for " + combatant, "New initiative", JOptionPane.QUESTION_MESSAGE);
                            initiative = Integer.parseInt(input);
                            ((Combatant) combatant).setInitiative(initiative);
                        } catch (NumberFormatException e) {
                            log.error("User input could not be parsed", e);
                        }
                    }
                }
                master.setCombatants(combatants);
                master.updateAll();
                break;
            case JOptionPane.NO_OPTION:
                master.startNewBattle();
                break;
            default:
                break;
        }
    }//GEN-LAST:event_bNewBattleActionPerformed

    private void miDiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDiceActionPerformed
        changeView("Dice");
    }//GEN-LAST:event_miDiceActionPerformed

    private void miAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAudioActionPerformed
        changeView("Audio");
    }//GEN-LAST:event_miAudioActionPerformed

    private void miSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSettingsActionPerformed
        changeView("Settings");
    }//GEN-LAST:event_miSettingsActionPerformed

    private void miBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBattleActionPerformed
        changeView("Battle");
    }//GEN-LAST:event_miBattleActionPerformed

    private void miCharactersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCharactersActionPerformed
        changeView("Characters");
    }//GEN-LAST:event_miCharactersActionPerformed

    private void miShutdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miShutdownActionPerformed
        this.dispose();
    }//GEN-LAST:event_miShutdownActionPerformed

    private void miClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientsActionPerformed
        changeView("Clients");
        refreshClientsTable();
    }//GEN-LAST:event_miClientsActionPerformed

    private void refreshClientsTable() {
        DefaultTableModel model = (DefaultTableModel) tClients.getModel();
        model.setRowCount(0);
        master.getSlaves().forEach((client) -> {
            String ip = null;
            String name = null;
            try {
                ip = client.getIp();
            } catch (RemoteException ex) {
                log.error("Error retrieveing remote ip", ex);
            }
            try {
                name = client.getName();
            } catch (RemoteException ex) {
                log.error("Error retrieveing remote name", ex);
            }
            model.addRow(new Object[]{ip, name});
        });
    }

    private void bKickClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKickClientActionPerformed
        int selectedRow = tClients.getSelectedRow();
        if (selectedRow >= 0) {
            try {
                master.kick(master.getSlaves().get(selectedRow));
            } catch (RemoteException ex) {
                log.error("Unable to kick remote connection.", ex);
            }
            refreshClientsTable();
        }
    }//GEN-LAST:event_bKickClientActionPerformed

    private void changeView(String cardName) {
        CardLayout layout = (CardLayout) (pView.getLayout());
        layout.show(pView, cardName);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddCombatant;
    private javax.swing.JButton bKickClient;
    private javax.swing.JButton bNewBattle;
    private javax.swing.JButton bNext;
    private com.wouter.dndbattle.view.master.DicePanel dicePanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mView;
    private javax.swing.JMenuItem miAudio;
    private javax.swing.JMenuItem miBattle;
    private javax.swing.JMenuItem miCharacters;
    private javax.swing.JMenuItem miClients;
    private javax.swing.JMenuItem miDice;
    private javax.swing.JMenuItem miSettings;
    private javax.swing.JMenuItem miShutdown;
    private com.wouter.dndbattle.view.master.AudioPanel pAudio;
    private javax.swing.JPanel pClients;
    private javax.swing.JPanel pCombatants;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pView;
    private javax.swing.JPopupMenu.Separator sMenu1;
    private javax.swing.JPopupMenu.Separator sMenu2;
    private com.wouter.dndbattle.view.master.SettingsPanel settingsPanel;
    private javax.swing.JScrollPane spClientsTable;
    private javax.swing.JScrollPane spCombatants;
    private javax.swing.JScrollPane spDice;
    private javax.swing.JScrollPane spSettings;
    private javax.swing.JTable tClients;
    private javax.swing.JTabbedPane tpBase;
    private javax.swing.JTabbedPane tpBattle;
    private javax.swing.JTabbedPane tpCharacters;
    // End of variables declaration//GEN-END:variables

    public void refreshBattle(final List<ICombatant> combatants, int activeIndex) {
        pCombatants.removeAll();
        while (tpBattle.getTabCount() > 1) {
            tpBattle.remove(1);
        }
        List<ICharacter> characters = new ArrayList<>();
        log.debug("Removed all from view to leave a total of [{}] components in the view", pCombatants.getComponents().length);
        for (int i = activeIndex; i < combatants.size(); i++) {
            final Combatant combatant = (Combatant) combatants.get(i);
            addCombatant(combatant);
            characters.add(combatant.getCharacter());
        }
        for (int i = 0; i < activeIndex; i++) {
            final Combatant combatant = (Combatant) combatants.get(i);
            addCombatant(combatant);
            characters.add(combatant.getCharacter());
        }
        Collections.sort(characters);
        ICharacter previousCharacter = null;
        for (ICharacter character : characters) {
            if (!character.equals(previousCharacter)) {
                tpBattle.add(new SlaveCharacterPanel(character));
                previousCharacter = character;
            }
        }
        log.debug("Added all combatants to get a new total of [{}] components in the view", pCombatants.getComponents().length);
        if (pCombatants.getComponents().length == 0) {
            pCombatants.add(new JPanel());
        }
        pCombatants.revalidate();
    }

    private void addCombatant(Combatant combatant) {
        log.debug("Adding {} of class {}", combatant, combatant.getClass());
        pCombatants.add(new MasterCombatantPanel(master, combatant));
    }

    private void addTabsToTpCharacter() {
        for (Class clazz : ClassComboBox.getAllClasses()) {
            tpCharacters.addTab(clazz.getSimpleName(), new MasterCharactersPanel(clazz));
        }
    }
}
