/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.wouter.randomizer.view;

import com.wouter.randomizer.Main;
import com.wouter.randomizer.randomizers.Randomizer;

public class OnetimeRandomizerPanel extends AbstractRandomizerPanel<Randomizer> {

  public OnetimeRandomizerPanel(Randomizer randomizer) {
    super(randomizer);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    lName = new javax.swing.JLabel();
    bGetSelection = new javax.swing.JButton();
    lOutput = new javax.swing.JLabel();
    bEdit = new javax.swing.JButton();

    setLayout(new java.awt.GridBagLayout());

    lName.setText(getRandomizer().getName());
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    add(lName, gridBagConstraints);

    bGetSelection.setText("Get selection");
    bGetSelection.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bGetSelectionActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
    add(bGetSelection, gridBagConstraints);

    lOutput.setVerticalAlignment(javax.swing.SwingConstants.TOP);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridheight = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.weightx = 1.0;
    gridBagConstraints.weighty = 1.0;
    add(lOutput, gridBagConstraints);

    bEdit.setText("Edit");
    bEdit.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bEditActionPerformed(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_START;
    add(bEdit, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void bGetSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGetSelectionActionPerformed
    setOutput(lOutput);
  }//GEN-LAST:event_bGetSelectionActionPerformed

  private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
    Main.getInstance().changeRight(getRandomizer());
  }//GEN-LAST:event_bEditActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bEdit;
  private javax.swing.JButton bGetSelection;
  private javax.swing.JLabel lName;
  private javax.swing.JLabel lOutput;
  // End of variables declaration//GEN-END:variables
}
