/*
 * Copyright (C) 2018 Wouter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wouter.dndbattle.view.master;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

import javax.swing.JLabel;
import javax.swing.JSpinner;

/**
 *
 * @author Wouter
 */
public class DicePanel extends javax.swing.JPanel {

    private static final Random random = new Random();
    private final List<DiceInfo> dice = new ArrayList<>(6);

    /**
     * Creates new form DicePanel
     */
    public DicePanel() {
        initComponents();
        dice.add(new DiceInfo(4, sD4, lD4numbers, lD4total));
        dice.add(new DiceInfo(6, sD6, lD6numbers, lD6total));
        dice.add(new DiceInfo(8, sD8, lD8numbers, lD8total));
        dice.add(new DiceInfo(10, sD10, lD10numbers, lD10total));
        dice.add(new DiceInfo(12, sD12, lD12numbers, lD12total));
        dice.add(new DiceInfo(20, sD20, lD20numbers, lD20total));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sD4 = new javax.swing.JSpinner();
        lD4 = new javax.swing.JLabel();
        sD6 = new javax.swing.JSpinner();
        lD6 = new javax.swing.JLabel();
        sD8 = new javax.swing.JSpinner();
        lD8 = new javax.swing.JLabel();
        sD10 = new javax.swing.JSpinner();
        lD10 = new javax.swing.JLabel();
        sD12 = new javax.swing.JSpinner();
        lD12 = new javax.swing.JLabel();
        sD20 = new javax.swing.JSpinner();
        lD20 = new javax.swing.JLabel();
        lD4numbers = new javax.swing.JLabel();
        lD6numbers = new javax.swing.JLabel();
        lD8numbers = new javax.swing.JLabel();
        lD10numbers = new javax.swing.JLabel();
        lD12numbers = new javax.swing.JLabel();
        lD20numbers = new javax.swing.JLabel();
        lD4total = new javax.swing.JLabel();
        lD6total = new javax.swing.JLabel();
        lD8total = new javax.swing.JLabel();
        lD10total = new javax.swing.JLabel();
        lD12total = new javax.swing.JLabel();
        lD20total = new javax.swing.JLabel();
        lTotal = new javax.swing.JLabel();
        bThrow = new javax.swing.JButton();

        sD4.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD4.setText("d4");

        sD6.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD6.setText("d6");

        sD8.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD8.setText("d8");

        sD10.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD10.setText("d10");

        sD12.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD12.setText("d12");

        sD20.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lD20.setText("d20");

        lD4numbers.setText(" ");

        lD6numbers.setText(" ");

        lD8numbers.setText(" ");

        lD10numbers.setText(" ");

        lD12numbers.setText(" ");

        lD20numbers.setText(" ");

        lD4total.setText(" ");

        lD6total.setText(" ");

        lD8total.setText(" ");

        lD10total.setText(" ");

        lD12total.setText(" ");

        lD20total.setText(" ");

        lTotal.setText(" ");

        bThrow.setText("Throw");
        bThrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThrowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sD20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lD20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD12numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lD20numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lD20total, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD12total, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD4numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lD6numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lD8numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lD10numbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lD10total, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD8total, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD6total, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lD4total, javax.swing.GroupLayout.Alignment.TRAILING)))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(bThrow)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lTotal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD4)
                    .addComponent(lD4numbers)
                    .addComponent(lD4total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD6)
                    .addComponent(lD6numbers)
                    .addComponent(lD6total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD8)
                    .addComponent(lD8numbers)
                    .addComponent(lD8total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD10)
                    .addComponent(lD10numbers)
                    .addComponent(lD10total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD12)
                    .addComponent(lD12numbers)
                    .addComponent(lD12total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sD20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lD20)
                    .addComponent(lD20numbers)
                    .addComponent(lD20total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTotal)
                    .addComponent(bThrow)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bThrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThrowActionPerformed
        int total = 0;
        total = dice.stream().map((die) -> die.throwDice()).reduce(total, Integer::sum);
        lTotal.setText(DiceInfo.TOTAL + total);
    }//GEN-LAST:event_bThrowActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bThrow;
    private javax.swing.JLabel lD10;
    private javax.swing.JLabel lD10numbers;
    private javax.swing.JLabel lD10total;
    private javax.swing.JLabel lD12;
    private javax.swing.JLabel lD12numbers;
    private javax.swing.JLabel lD12total;
    private javax.swing.JLabel lD20;
    private javax.swing.JLabel lD20numbers;
    private javax.swing.JLabel lD20total;
    private javax.swing.JLabel lD4;
    private javax.swing.JLabel lD4numbers;
    private javax.swing.JLabel lD4total;
    private javax.swing.JLabel lD6;
    private javax.swing.JLabel lD6numbers;
    private javax.swing.JLabel lD6total;
    private javax.swing.JLabel lD8;
    private javax.swing.JLabel lD8numbers;
    private javax.swing.JLabel lD8total;
    private javax.swing.JLabel lTotal;
    private javax.swing.JSpinner sD10;
    private javax.swing.JSpinner sD12;
    private javax.swing.JSpinner sD20;
    private javax.swing.JSpinner sD4;
    private javax.swing.JSpinner sD6;
    private javax.swing.JSpinner sD8;
    // End of variables declaration//GEN-END:variables

    private static class DiceInfo {

        private static final String EMPTY = " ";
        private static final String SEPARATOR = ", ";
        private static final String TOTAL = "Total: ";

        private final int sides;
        private final JSpinner sDice;
        private final JLabel lNumbers;
        private final JLabel lTotal;

        public DiceInfo(int sides, JSpinner sDice, JLabel lNumbers, JLabel lTotal) {
            this.sides = sides;
            this.sDice = sDice;
            this.lNumbers = lNumbers;
            this.lTotal = lTotal;
        }

        private int throwDice() {
            int dice = (Integer) sDice.getValue();
            if (dice < 1) {
                lNumbers.setText(EMPTY);
                lTotal.setText(EMPTY);
                return 0;
            }
            String[] throwResults = new String[dice];
            int total = 0;
            for (int i = 0; i < throwResults.length; i++) {
                int throwResult = random.nextInt(sides) + 1;
                throwResults[i] = throwResult + "";
                total += throwResult;
            }
            lNumbers.setText(String.join(SEPARATOR, throwResults));
            lTotal.setText(TOTAL + total);
            return total;
        }
    }
}
