/*
 * Copyright (C) 2018 wverl
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wouter.dndbattle.view.master.encounter;

import static com.wouter.dndbattle.utils.EncounterXpCalculator.*;

import java.awt.Component;
import java.awt.event.ItemEvent;
import java.util.HashMap;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.ListModel;

import com.wouter.dndbattle.objects.ICharacter;
import com.wouter.dndbattle.objects.impl.character.Enemy;
import com.wouter.dndbattle.objects.impl.character.Player;
import com.wouter.dndbattle.utils.Characters;

/**
 *
 * @author wverl
 */
public class EncounterCalculator extends javax.swing.JPanel {

    private static final Characters CHARACTERS = Characters.getInstance();
    private final Map<ICharacter, EncounterCombantantPanel> friendlyCharacterPanelMap = new HashMap<>();
    private final Map<ICharacter, EncounterCombantantPanel> enemyCharacterPanelMap = new HashMap<>();

    /**
     * Creates new form EncounterCalculator
     */
    public EncounterCalculator() {
        initComponents();
    }

    public void updateLabels() {
        int easyTotal = 0;
        int mediumTotal = 0;
        int hardTotal = 0;
        int deathlyTotal = 0;
        int dailyTotal = 0;
        int party = 0;
        for (Component component : pFriendlyCombatants.getComponents()) {
            if (component instanceof EncounterCombantantPanel) {
                EncounterCombantantPanel ecp = (EncounterCombantantPanel) component;
                int level = ecp.getLevel();
                int amount = ecp.getAmount();
                easyTotal += (getEasyExperience(level) * amount);
                mediumTotal += (getMediumExperience(level) * amount);
                hardTotal += (getHardExperience(level) * amount);
                deathlyTotal += (getDeathlyExperience(level) * amount);
                dailyTotal += (getDailyExperience(level) * amount);
                party += amount;
            }
        }
        lEasy.setText(Integer.toString(easyTotal));
        lMedium.setText(Integer.toString(mediumTotal));
        lHard.setText(Integer.toString(hardTotal));
        lDeathly.setText(Integer.toString(deathlyTotal));
        lDaily.setText(Integer.toString(dailyTotal));

        long totalExp = 0;
        int amountOfEnemies = 0;
        for (Component component : pEnemyCombatants.getComponents()) {
            if (component instanceof EncounterCombantantPanel) {
                EncounterCombantantPanel ecp = (EncounterCombantantPanel) component;
                int amount = ecp.getAmount();
                totalExp += (ecp.getExp() * amount);
                amountOfEnemies += amount;
            }
        }
        lTotal.setText(Long.toString(totalExp));
        double multiplier = getEncounterMultiplier(party, amountOfEnemies);
        lMultiplier.setText(Double.toString(multiplier));
        int adjusted = (int) (multiplier * (double) totalExp);
        lAdjusted.setText(Integer.toString(adjusted));

        if (adjusted < easyTotal) {
            lResult.setText("Very Easy");
        } else if (adjusted < mediumTotal) {
            lResult.setText("Easy");
        } else if (adjusted < hardTotal) {
            lResult.setText("Medium");
        } else if (adjusted < deathlyTotal) {
            lResult.setText("Hard");
        } else if (adjusted < deathlyTotal) {
            lResult.setText("Deathly");
        } else {
            lResult.setText("DAILY!!!");
        }
    }

    private ListModel<ICharacter> getListModel(Class<? extends ICharacter> clazz) {
        DefaultListModel<ICharacter> model = new DefaultListModel<>();
        CHARACTERS.getCharacters(clazz).forEach((character) -> {
            model.addElement(character);
        });
        return model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        cbFriendlyClass = new com.wouter.dndbattle.view.comboboxes.ClassComboBox();
        splFriendly = new javax.swing.JScrollPane();
        lFriendly = new javax.swing.JList<>();
        bAddFriendly = new javax.swing.JButton();
        splFriendlyCombatants = new javax.swing.JScrollPane();
        pFriendlyCombatants = new javax.swing.JPanel();
        lEasyText = new javax.swing.JLabel();
        lEasy = new javax.swing.JLabel();
        lMediumTest = new javax.swing.JLabel();
        lMedium = new javax.swing.JLabel();
        lHardText = new javax.swing.JLabel();
        lHard = new javax.swing.JLabel();
        lDeathlyText = new javax.swing.JLabel();
        lDeathly = new javax.swing.JLabel();
        lDailyText = new javax.swing.JLabel();
        lDaily = new javax.swing.JLabel();
        sMiddle = new javax.swing.JSeparator();
        spEnemyCombatants = new javax.swing.JScrollPane();
        pEnemyCombatants = new javax.swing.JPanel();
        bAddEnemy = new javax.swing.JButton();
        cbEnemyClass = new com.wouter.dndbattle.view.comboboxes.ClassComboBox();
        splEnemy = new javax.swing.JScrollPane();
        lEnemy = new javax.swing.JList<>();
        lTotal = new javax.swing.JLabel();
        lTotalText = new javax.swing.JLabel();
        lMultiplier = new javax.swing.JLabel();
        lMultiplierText = new javax.swing.JLabel();
        lAdjusted = new javax.swing.JLabel();
        lAdjustedText = new javax.swing.JLabel();
        lResult = new javax.swing.JLabel();
        lResultText = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        cbFriendlyClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFriendlyClassItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(cbFriendlyClass, gridBagConstraints);

        lFriendly.setModel(getListModel(Player.class));
        splFriendly.setViewportView(lFriendly);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(splFriendly, gridBagConstraints);

        bAddFriendly.setText(">");
        bAddFriendly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddFriendlyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(bAddFriendly, gridBagConstraints);

        pFriendlyCombatants.setLayout(new java.awt.GridLayout(0, 1));
        splFriendlyCombatants.setViewportView(pFriendlyCombatants);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(splFriendlyCombatants, gridBagConstraints);

        lEasyText.setText("Easy");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lEasyText, gridBagConstraints);

        lEasy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lEasy, gridBagConstraints);

        lMediumTest.setText("Medium");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lMediumTest, gridBagConstraints);

        lMedium.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lMedium, gridBagConstraints);

        lHardText.setText("Hard");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lHardText, gridBagConstraints);

        lHard.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lHard, gridBagConstraints);

        lDeathlyText.setText("Deathly");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lDeathlyText, gridBagConstraints);

        lDeathly.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lDeathly, gridBagConstraints);

        lDailyText.setText("Daily");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(lDailyText, gridBagConstraints);

        lDaily.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(lDaily, gridBagConstraints);

        sMiddle.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(sMiddle, gridBagConstraints);

        pEnemyCombatants.setLayout(new java.awt.GridLayout(0, 1));
        spEnemyCombatants.setViewportView(pEnemyCombatants);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(spEnemyCombatants, gridBagConstraints);

        bAddEnemy.setText("<");
        bAddEnemy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddEnemyActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(bAddEnemy, gridBagConstraints);

        cbEnemyClass.setSelectedItem(Enemy.class);
        cbEnemyClass.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEnemyClassItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(cbEnemyClass, gridBagConstraints);

        lEnemy.setModel(getListModel(Enemy.class));
        splEnemy.setViewportView(lEnemy);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(splEnemy, gridBagConstraints);

        lTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lTotal, gridBagConstraints);

        lTotalText.setText("Total XP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(lTotalText, gridBagConstraints);

        lMultiplier.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lMultiplier, gridBagConstraints);

        lMultiplierText.setText("Multiplier");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(lMultiplierText, gridBagConstraints);

        lAdjusted.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(lAdjusted, gridBagConstraints);

        lAdjustedText.setText("Adjusted XP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(lAdjustedText, gridBagConstraints);

        lResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(lResult, gridBagConstraints);

        lResultText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lResultText.setText("Result");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lResultText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void cbFriendlyClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFriendlyClassItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            final DefaultListModel model = (DefaultListModel) lFriendly.getModel();
            model.removeAllElements();
            lFriendly.clearSelection();
            CHARACTERS.getCharacters(cbFriendlyClass.getSelectedItem()).forEach((character) -> {
                model.addElement(character);
            });
        }
    }//GEN-LAST:event_cbFriendlyClassItemStateChanged

    private void bAddFriendlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddFriendlyActionPerformed
        addCharacter(lFriendly, friendlyCharacterPanelMap, pFriendlyCombatants);
    }//GEN-LAST:event_bAddFriendlyActionPerformed

    private void bAddEnemyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddEnemyActionPerformed
        addCharacter(lEnemy, enemyCharacterPanelMap, pEnemyCombatants);
    }//GEN-LAST:event_bAddEnemyActionPerformed

    private void addCharacter(JList<ICharacter> list, Map<ICharacter, EncounterCombantantPanel> map, JPanel panel) {
        ICharacter selectedValue = list.getSelectedValue();
        if (selectedValue != null) {
            if (map.containsKey(selectedValue)) {
                map.get(selectedValue).addOne();
            } else {
                final EncounterCombantantPanel ecp = new EncounterCombantantPanel(this, selectedValue);
                map.put(selectedValue, ecp);
                panel.add(ecp);
            }
            updateLabels();
        }
    }

    private void cbEnemyClassItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEnemyClassItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            final DefaultListModel model = (DefaultListModel) lEnemy.getModel();
            model.removeAllElements();
            lEnemy.clearSelection();
            CHARACTERS.getCharacters(cbEnemyClass.getSelectedItem()).forEach((character) -> {
                model.addElement(character);
            });
        }
    }//GEN-LAST:event_cbEnemyClassItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddEnemy;
    private javax.swing.JButton bAddFriendly;
    private com.wouter.dndbattle.view.comboboxes.ClassComboBox cbEnemyClass;
    private com.wouter.dndbattle.view.comboboxes.ClassComboBox cbFriendlyClass;
    private javax.swing.JLabel lAdjusted;
    private javax.swing.JLabel lAdjustedText;
    private javax.swing.JLabel lDaily;
    private javax.swing.JLabel lDailyText;
    private javax.swing.JLabel lDeathly;
    private javax.swing.JLabel lDeathlyText;
    private javax.swing.JLabel lEasy;
    private javax.swing.JLabel lEasyText;
    private javax.swing.JList<ICharacter> lEnemy;
    private javax.swing.JList<ICharacter> lFriendly;
    private javax.swing.JLabel lHard;
    private javax.swing.JLabel lHardText;
    private javax.swing.JLabel lMedium;
    private javax.swing.JLabel lMediumTest;
    private javax.swing.JLabel lMultiplier;
    private javax.swing.JLabel lMultiplierText;
    private javax.swing.JLabel lResult;
    private javax.swing.JLabel lResultText;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotalText;
    private javax.swing.JPanel pEnemyCombatants;
    private javax.swing.JPanel pFriendlyCombatants;
    private javax.swing.JSeparator sMiddle;
    private javax.swing.JScrollPane spEnemyCombatants;
    private javax.swing.JScrollPane splEnemy;
    private javax.swing.JScrollPane splFriendly;
    private javax.swing.JScrollPane splFriendlyCombatants;
    // End of variables declaration//GEN-END:variables
}
