/*
 * Copyright (C) 2018 Wouter
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.wouter.dndbattle.view.master.character;

import java.awt.Component;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.List;

import com.wouter.dndbattle.objects.ICharacterClass;
import com.wouter.dndbattle.objects.impl.AbstractCharacter;
import com.wouter.dndbattle.objects.impl.AbstractExtendedCharacter;
import com.wouter.dndbattle.view.master.character.abiliyAndSkill.AbilityAndSkillPanel;
import com.wouter.dndbattle.view.master.character.extendedCharacter.ExtendedCharacterPanel;
import com.wouter.dndbattle.view.master.character.spells.SpellOverviewPanel;
import com.wouter.dndbattle.view.master.character.weapon.WeaponsPanel;
import com.wouter.dndbattle.view.master.MasterCharactersPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Wouter
 */
public class CharacterPanel extends javax.swing.JPanel implements IUpdateablePanel {

    private static final Logger log = LoggerFactory.getLogger(CharacterPanel.class);

    private final AbstractCharacter character;
    private final MasterCharactersPanel presetPanel;

    public CharacterPanel(AbstractCharacter character) {
        this(character, null);
    }

    public CharacterPanel(AbstractCharacter character, MasterCharactersPanel presetPanel) {
        this.character = character;
        this.presetPanel = presetPanel;
        initComponents();
    }

    public void updateAll() {
        if (presetPanel != null) {
            presetPanel.updateList();
        }
        update();
    }

    public int getCurrentTab() {
        return tpCharacterPages.getSelectedIndex();
    }

    public void setCurrentTab(int currentTab) {
        tpCharacterPages.setSelectedIndex(currentTab);
    }

    @Override
    public void update() {
        for (Component component : tpCharacterPages.getComponents()) {
            if (component instanceof IUpdateablePanel) {
                ((IUpdateablePanel) component).update();
            }
        }
    }

    private void createTabs() {
        tpCharacterPages.addTab("Abilities", new AbilityAndSkillPanel(character, this));
        if (character instanceof AbstractExtendedCharacter) {
            tpCharacterPages.addTab("Character", new ExtendedCharacterPanel((AbstractExtendedCharacter) character, this));
        }
        tpCharacterPages.addTab("Weapons", new WeaponsPanel(character, this));
        tpCharacterPages.addTab("Spells", new SpellOverviewPanel(character));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lName = new javax.swing.JLabel();
        tpCharacterPages = new javax.swing.JTabbedPane();

        lName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lName.setText(character.getName());
        lName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lNameMouseClicked(evt);
            }
        });

        tpCharacterPages.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tpCharacterPages.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        createTabs();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lName, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
            .addComponent(tpCharacterPages, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpCharacterPages, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lNameMouseClicked
        if (Desktop.getDesktop().isSupported(Desktop.Action.BROWSE)) {
            String searchQuery;
            if (character instanceof AbstractExtendedCharacter) {
                List<ICharacterClass> classes = ((AbstractExtendedCharacter) character).getCharacterClasses();
                if (classes == null || classes.isEmpty()) {
                    return;
                }
                searchQuery = classes.get(0).getName();
            } else {
                searchQuery = character.getName();
            }
            try {
                Desktop.getDesktop().browse(new URI("https://roll20.net/compendium/dnd5e/searchbook/?terms=" + searchQuery.replace(" ", "%20")));
            } catch (IOException | URISyntaxException e) {
                log.error("Error while opening search in browser", e);
            }
        }
    }//GEN-LAST:event_lNameMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lName;
    private javax.swing.JTabbedPane tpCharacterPages;
    // End of variables declaration//GEN-END:variables
}
